kortix-ai/suna

backend/services/redis.py

This pull request includes a small update to the `initialize` method in `backend/services/redis.py`. The change ensures that the `REDIS_SSL` environment variable is properly converted from a string ('True'/'False') to a boolean value.
* [`backend/services/redis.py`](diffhunk://#diff-290e53607a21739ecd0374ebb30506d829b28559f6bdc9bf8a3abc46e82217bbL28-R30): Added logic to convert the `REDIS_SSL` environment variable from a string to a boolean for proper handling.

fix: update Redis SSL environment variable handling

---

backend/agentpress/response_processor.py

Bug fix in tool parameter extraction.
The previous implementation was improperly using mapping.path for attribute names.
All parameters were assigned the same value as a first parameter.
This fix allows all parameters to be passed properly to the agent tools.

Fix: proper param_name for tool parameter mapping

---

frontend/src/app/(dashboard)/layout.tsx
frontend/src/components/sidebar/nav-agents.tsx
frontend/src/components/thread/DeleteConfirmationDialog.tsx
frontend/src/components/ui/status-overlay.tsx
frontend/src/contexts/DeleteOperationContext.tsx
frontend/src/lib/api.ts

This PR implements a complete thread deletion functionality with safeguards to prevent UI freezing during deletion operations. It provides users with a confirmation dialog before deletion and ensures that the interface remains responsive throughout the process.
Previously, there was no way to delete threads, which could lead to clutter in the sidebar. When implementing deletion functionality, there were UI responsiveness issues during the deletion process, particularly when deleting threads that were not currently active. This implementation solves those issues with a robust architecture.
- **DeleteConfirmationDialog**: A modal dialog that requests user confirmation before thread deletion
- **DeleteOperationContext**: A React context for centralized state management of deletion operations …

Add thread deletion with confirmation dialog and improved UI interaction

---

backend/agent/api.py
backend/agent/run.py
backend/agent/tools/message_tool.py
backend/agentpress/thread_manager.py
backend/services/llm.py
frontend/src/components/thread/chat-input.tsx

This pull request introduces enhancements to model selection and logging, along with improvements in API behavior and frontend handling. Key updates include the addition of model aliasing, default model configuration, refined logging for better traceability, and adjustments to frontend model handling logic.
**Model Selection and Aliasing:**
* Introduced `MODEL_NAME_ALIASES` to map short model names to their full names and ensure consistency in model resolution. Default model selection now uses `config.MODEL_TO_USE` if no model is specified in requests (`backend/agent/api.py`). [[1]](diffhunk://#diff-4009f6c53c4cc022ad34a0ab0faaf392c5a2fa7473b09e9e99b2f471eb23c8ebR35-R59) [[2]](diffhunk://#diff-4009f6c53c4cc022ad34a0ab0faaf392c5a2fa7473b09e9e99b2f471eb23c8ebL358-R389) …

Implementation of choosing between OPENAI/Antropic models by setting MODEL_TO_USE

---

backend/utils/logger.py

This small PR resolves the `datetime` library warnings:
```python
DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC). or datetime.datetime.utcnow()
```
Note that `.replace(tzinfo=None)` allows to keep the original behavior where the time appears as a naive UTC timestamp (i.e., without any timezone offset).

Migrate to modern datetime library API

---

setup.py

This pull request re-enables previously commented-out sections of the `main()` function in `setup.py` to restore functionality for collecting Supabase and Daytona information during the setup process.
Restored functionality:
* Re-enabled the steps for collecting Supabase information, including setting the `SUPABASE_URL` environment variable. (`[setup.pyL827-R836](diffhunk://#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L827-R836)`)
* Re-enabled the steps for collecting Daytona information. (`[setup.pyL827-R836](diffhunk://#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L827-R836)`)

hotfix(setup): uncomment required steps

---

backend/sandbox/sandbox.py
backend/utils/config.py
setup.py

This pull request introduces a centralized configuration class (`Config`) for managing sandbox-related constants, replacing hardcoded values with references to the new class across the codebase. This change improves maintainability and reduces duplication.
* [`backend/config.py`](diffhunk://#diff-651976572b51d1a16ede6a1c4c1be9a1482605ce57ca58fbfca25e4a55c43210R1-R3): Added a new `Config` class with constants `SANDBOX_IMAGE_NAME` and `SANDBOX_ENTRYPOINT` to centralize sandbox configuration.
* `backend/sandbox/sandbox.py`:
- Imported the `Config` class for use in sandbox-related operations.
- Updated the `create_sandbox` function to use `Config.SANDBOX_IMAGE_NAME` instead of a hardcoded image name.
* `setup.py`:
- Replaced hardcoded sandbox image name and entrypoint in …

chore(config): refactor sandbox image constants into common config

---

README.md
docs/SELF-HOSTING.md
start.py

This pull request introduces a new script, `start.py`, to interactively manage Docker Compose services. The script provides options to start or stop containers with user confirmation and includes a force mode to bypass prompts.
* **Interactive Docker Compose management**: The script determines whether Docker Compose services are running and prompts the user to start or stop them based on their current state.
* **Command-line options**: Added support for `--help` to display usage information and `-f` to enable force mode, skipping user confirmation.

feat(start): added container starter/stopper script

---

setup.py

This pull request includes a change to the `configure_frontend_env` function in `setup.py` to simplify the backend URL configuration and add a new environment variable for the frontend.
* [`setup.py`](diffhunk://#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L526-R533): Removed the conditional logic for determining the backend URL, defaulting it to `http://localhost:8000/api` regardless of whether Docker is used. Added a new environment variable, `NEXT_PUBLIC_ENV_MODE`, set to `'LOCAL'`.

hotfix(setup): backend url fix

---

frontend/src/app/auth/page.tsx
frontend/src/components/GoogleSignIn.tsx

**What This PR Does**
- Improves readability of the "Forgot Password" dialog in dark mode by increasing its background opacity to reduce visual conflict between background and foreground text.
- Removes the default dialog close button to prevent duplication, as a custom close button is already implemented and visible.
Fixes #383 
**Screenshot**
These changes enhance the user experience and accessibility, particularly in dark theme environments.

fix: improve forgot password dialog opacity and remove duplicate close button

---

setup.py

Fixes #365 and #364 
This pull request updates the `setup.py` file by removing a dependency on the `Configuration` class and replacing it with hardcoded values for better clarity and independence. Below are the key changes:
* Removed the import statement for `Configuration` from `backend.utils.config`, as it is no longer used in the script.
* Replaced `Configuration.SANDBOX_IMAGE_NAME` with the hardcoded value `'kortix/suna:0.1.2'` for the image name.
* Replaced `Configuration.SANDBOX_ENTRYPOINT` with the hardcoded value `'/usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf'` for the Entrypoint.

hotfix(setup): setup fails without a .env file

---

frontend/src/app/api/share-page/og-image/route.tsx

Problem:
- there's lag in loading the OG image on share pages(Orshot returns it in ~1s but the route is currently taking ~2 to 4s to return it)
Solution:
- updated the function to run on edge, added caching(~1 to 2seconds reduction in rendering time)

fix: generate share page og image on edge

---

backend/utils/constants.py
frontend/src/components/thread/chat-input/_use-model-selection.ts

Adjust model priorities in the frontend selector to place Kimi K2 second and Grok 4 third.
---
[Slack Thread](https://kortixworkspace.slack.com/archives/C09616XFV9A/p1752667955427869?thread_ts=1752667955.427869&cid=C09616XFV9A)

Reorder models in frontend selector

---

frontend/src/app/(dashboard)/agents/page.tsx
frontend/src/components/agents/custom-agents-page/marketplace-tab.tsx
frontend/src/components/agents/custom-agents-page/my-agents-tab.tsx
frontend/src/components/ui/fancy-tabs.tsx

Fix conflicting hover state on active `FancyTabs` and optimize inactive tab hover effects.
The previous hover styling on active tabs created a visual conflict with the active background, resulting in a 'weird' appearance. This PR removes the hover effect on active tabs and enhances the hover feedback for inactive tabs.
---
[Slack Thread](https://kortixworkspace.slack.com/archives/C08QYH7MV6F/p1752748743222729?thread_ts=1752748743.222729&cid=C08QYH7MV6F)

Optimize agents page switcher states

---

frontend/src/components/ui/scroll-area.tsx

Resolves content overflow issues in the right panel caused by the ScrollArea component's internal div with 'min-width:100%;display:table' styling. This addresses the known shadcn-ui ScrollArea limitation where the component takes up the entire width and causes overflow.
The fix ensures proper width constraints while maintaining scroll functionality.
References: https://github.com/shadcn-ui/ui/issues/3833

fix: prevent right panel content overflow in ScrollArea component

---

frontend/package.json

There's a phantom package in the `frontend/src/components/file-renderers/code-renderer.tsx` that is not included in package.json, which may cause potential dependency issues.
```tsx
import { EditorView } from '@codemirror/view';
```

fix: phantom dependency

---

backend/sandbox/docker/requirements.txt

Adds pandas dependency to sandbox environment to fix ModuleNotFoundError when agents process Excel files. Fixes #1043

fix: add pandas to sandbox requirements to resolve ModuleNotFoundError (#1043)

---

frontend/src/components/thread/content/PlaybackControls.tsx

When clicking the reset button, the right panel doesn't hide.

fix: hide panel when resetting the state of playback

---

frontend/src/app/share/[threadId]/page.tsx
frontend/src/components/thread/content/PlaybackControls.tsx
frontend/src/components/thread/content/ThreadContent.tsx
frontend/src/components/thread/tool-call-side-panel.tsx
frontend/src/components/thread/utils.ts
frontend/src/components/ui/slider.tsx

This PR is mainly for fixing the index of tools in playback mode. Right now, the streaming text is synchronized with the tool index.
https://github.com/user-attachments/assets/7da6f18b-d380-4c4a-b514-188bd95efdce
- Remove unused toolName tracking in chunk processing (Right now, all tool names are `function–call`, which are useless for parsing tool names)
- Simplify tool call handling in PlaybackControls by removing toolPlaybackIndex state
- Fix tool navigation initialization and synchronization issues
- Consolidate HIDE_STREAMING_XML_TAGS constant from multiple files into utils.ts
- Add 'create-tasks' to hidden streaming XML tags list
- Improve tool call side panel index synchronization
- Add cursor pointer styling to slider components for better UX
- Fix tool index initialization to …

fix: refactor playback controls and consolidate XML tag constants

---

frontend/src/app/(dashboard)/projects/[projectId]/thread/[threadId]/page.tsx
frontend/src/hooks/useAgentStream.ts

Opening an old conversation thread triggered noisy errors and toasts:
- "[useAgentStream] Error initiating stream …: Agent run … is not running"
- "[PAGE] Stream hook error: Agent run … is not running"
Root cause: the UI auto-attempted to start a stream for historical agent runs that were already completed/stopped. The SSE hook then surfaced the expected "not running" response as an error.
This PR prevents unnecessary streaming attempts for inactive runs and treats these cases as expected (quiet) outcomes.
- Thread page: only auto-start streaming on initial load if the run status is explicitly `running`.
- Stream hook: treat 404/not-found/not-running as benign. Finalize gracefully without toasts and use info-level logs.
- Reduced error-toasts/logs when opening historical threads; status …

Fix: Avoid streaming for inactive agent runs when opening old threads

---

apps/mobile/components/RightPanel.tsx
apps/mobile/stores/ui-store.ts
frontend/src/components/thread/tool-call-side-panel.tsx

https://github.com/user-attachments/assets/ea8bd543-b46d-43d9-8302-02466160af30
This PR fixes the issue where the live updates button in tool side panel bugs out when clicked. This issue was reproducable when the user uses the slider to a certain step and then clicks on jump to latest. It will go to the latest step but then will stuck there and will not move along with the further steps. 
Fixes #1333.

fix : Clicking Live Updates skips to the latest. Sometimes it bugs out (fixes #1333)

---

frontend/src/lib/api.ts

- Added consistent EventSource cleanup helper function
- Fixed missing cleanup in error handlers that could cause memory leaks
- Added safety timeout (30min) to prevent indefinite connections
- Exported cleanup function for external use during app teardown
- Improved error logging and connection state tracking
Fixes the critical memory leak where EventSource connections weren't properly closed in all error scenarios, particularly in the catch blocks of the onerror handler.

fix: prevent EventSource memory leaks in frontend API
