kortix-ai/suna

- frontend/src/app/dashboard/agents/[threadId]/page.tsx
- frontend/src/components/thread/todo-panel.tsx
- frontend/src/components/thread/tool-call-side-panel.tsx
The issue was basically when you moved to the new frontend, it just didn't copy the entire streaming processing code... 
streaming is coming though the backend though, it is a frontend issue
> Streaming almost working again, no rendering though, and still very buggy

- frontend/src/components/home/sections/open-source-section.tsx
Fixes #120 
This PR updates the padding of the specific element as shown in images below on the home page
Before the Update
After the Update
> Added a top padding on Home page for specific div

- .github/workflows/docker-build.yml
- README.md
- backend/Dockerfile
- docker-compose.ghcr.yaml
- docker-compose.yaml
- frontend/Dockerfile
This pull request introduces Docker support for the project, including Dockerfiles, Docker Compose configurations, and updates to the documentation to reflect these changes. The goal is to streamline the setup process and provide an alternative to local installations by using containerized services.
* **GitHub Actions Workflow**: Added a new workflow in `.github/workflows/docker-build.yml` to build and push Docker images for the backend and frontend to the GitHub Container Registry. This includes setting up Docker Buildx and caching layers for efficiency.
* **Backend Dockerfile**: Created a `backend/Dockerfile` to containerize the backend application using Python 3.11. It installs dependencies from `requirements.txt` and sets up the application to run on port 8000.
* **Frontend …
> Dockerfiles for backend/frontend + github actions + docker-compose

- backend/services/redis.py
[fix redis ssl](https://github.com/kortix-ai/suna/commit/23a29377935fd1a2c70ae903c3142a46d00a0823)
> fix redis ssl

- README.md
teeny change lol
hopefully another pr from me incoming soon
> no more ass

- backend/Dockerfile
https://docs.gunicorn.org/en/latest/settings.html#keepalive
https://github.com/kortix-ai/suna/commit/a780e4c0d64a261c651cac782b6156d03b746447#diff-fed51f49a9f26cb93cc870efdc9419d425b9422354ae41bb651c3333c8bff486R46-R48
> Fixed --keep-alive

- README.md
updated instruction to use poetry for installation as well as running the backend.
> updated readme installation and start backend instruction

- frontend/src/components/file-renderers/binary-renderer.tsx
- frontend/src/components/file-renderers/index.tsx
- frontend/src/components/thread/attachment-group.tsx
- frontend/src/components/thread/chat-input/chat-input.tsx
- frontend/src/components/thread/file-attachment.tsx
- frontend/src/components/thread/file-viewer-modal.tsx
- frontend/src/components/thread/preview-renderers/csv-renderer.tsx
- frontend/src/hooks/use-cached-file.ts
- frontend/src/hooks/use-image-content.ts
Changes:
- added multiple fixes for file handling
> feat: fix download and other issues

- frontend/src/components/thread/file-viewer-modal.tsx
Fix:
-  try load files when there is no token
> fix: try load files if there is no token

- frontend/src/components/sidebar/nav-agents.tsx
- frontend/src/components/sidebar/nav-user-with-teams.tsx
- frontend/src/components/thread/chat-input/chat-input.tsx
- frontend/src/hooks/react-query/sidebar/keys.ts
- frontend/src/hooks/react-query/sidebar/use-sidebar.ts
This PR enhances the sidebar UX by adding multi-select capabilities and parallel bulk deletion. Users can now select multiple threads simultaneously and delete them in a single operation with progress tracking.
> chore(ux): added multiple select and delete functionality

- frontend/src/app/(dashboard)/agents/[threadId]/page.tsx
- frontend/src/hooks/react-query/threads/keys.ts
- frontend/src/hooks/react-query/threads/use-agent-run.ts
- frontend/src/hooks/react-query/threads/use-billing-status.ts
- frontend/src/hooks/react-query/threads/use-messages.ts
- frontend/src/hooks/react-query/threads/use-project.ts
- frontend/src/hooks/react-query/threads/use-threads.ts
This pull request focuses on refactoring the frontend codebase, specifically targeting the thread page. The goal of this refactor is to improve code readability, maintainability, and ensure consistency across hooks and API usage. The goal is to make the component structure cleaner and move the API calls to React Query
> chore(dev): frontend refactor - started with thread page

- docker-compose.yaml
The rabbitmq Service needs to be added to the docker compos file at the project root level
> Fixing issue with docker run

- frontend/src/app/share/[threadId]/layout.tsx
- frontend/src/app/share/[threadId]/page.tsx
- frontend/src/components/thread/content/PlaybackControls.tsx
- fixes issue in which header in `/share/*` pages are unclickable due to z-index issue
- added canonical url for share pages for SEO
> fix: z-index issue on share pages preventing clicks on header, also add canonical url

- backend/agent/api.py
- backend/services/billing.py
- backend/utils/constants.py
- frontend/src/components/sidebar/nav-agents.tsx
- frontend/src/components/thread/chat-input/_use-model-selection.ts
- frontend/src/components/thread/chat-input/model-selector.tsx
UX improvements:
- Added clear communication on the free models not being of high quality
- Added Qwen3 as a free model
- Hydration issues in sidebar fixed
> chore(ui): improvements in model selector

- setup.py
This pull request simplifies the `setup.py` script by removing support for certain LLM providers (`Groq` and `AWS Bedrock`) and commenting out unused sections related to Supabase and Daytona configuration. These changes streamline the setup process and reduce complexity.
* Removed support for `Groq` and `AWS Bedrock` as LLM providers, including their configuration options, API key prompts, and default model recommendations. (`[[1]](diffhunk://#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L224-R231)`, `[[2]](diffhunk://#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L249-R254)`, `[[3]](diffhunk://#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L270-L272)`, `[[4]](diffhunk://#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5 …
> chore(setup): remove additional LLM providers

- backend/agent/api.py
- backend/run_agent_background.py
- backend/sandbox/api.py
- frontend/src/app/(dashboard)/dashboard/page.tsx
- Removed the `get_or_create_project_sandbox` function from `agent/api.py` and replaced its usage with direct sandbox retrieval logic.
- Updated `start_agent` and `ensure_project_sandbox_active` functions to directly access sandbox information from project data.
- Cleaned up unnecessary comments and improved logging for sandbox operations.
- Adjusted frontend form submission to ensure consistent handling of FormData and improved error handling.
> fix(sandbox): streamline sandbox handling

- frontend/src/contexts/BillingContext.tsx
- frontend/src/hooks/react-query/threads/use-billing-status.ts
This PR attempts to fix the redundant billing check on the frontend (needs review)
> chore(dev): fix redundant billing checks

- frontend/src/app/(dashboard)/agents/[threadId]/page.tsx
This PR is a second time on attempt to fix repeated billing check status
> chore(dev): second attempt to fix billing checks

- backend/agent/tools/sb_shell_tool.py
- backend/docker-compose.yml
- frontend/src/app/(dashboard)/agents/[threadId]/page.tsx
- frontend/src/app/api/share-page/og-image/route.tsx
- frontend/src/components/maintenance/maintenance-page.tsx
- frontend/src/components/thread/tool-views/FileOperationToolView.tsx
- frontend/src/hooks/react-query/subscriptions/use-subscriptions.ts
This PR:
- Introduces a upgrade dialog that free tier user sees (only once), when the agent runs for the first time.
> Alert dialog on agent run in free tier

- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/globals.css
- frontend/src/components/thread/content/ThreadContent.tsx
- frontend/src/components/thread/content/loader.tsx
- frontend/src/components/thread/tool-call-side-panel.tsx
- frontend/src/components/thread/tool-views/BrowserToolView.tsx
- frontend/src/components/thread/tool-views/CommandToolView.tsx
- frontend/src/components/thread/tool-views/DataProviderToolView.tsx
- frontend/src/components/thread/tool-views/ExposePortToolView.tsx
- frontend/src/components/thread/tool-views/FileOperationToolView.tsx
- frontend/src/components/thread/tool-views/SeeImageToolView.tsx
- frontend/src/components/thread/tool-views/StrReplaceToolView.tsx
- frontend/src/components/thread/tool-views/WebCrawlToolView.tsx
- frontend/src/components/thread/tool-views/WebScrapeToolView.tsx
- frontend/src/components/thread/tool-views/WebSearchToolView.tsx
- frontend/src/components/thread/tool-views/wrapper/ToolViewRegistry.tsx
- frontend/src/components/thread/utils.ts
- frontend/src/components/ui/skeleton.tsx
- frontend/src/hooks/react-query/threads/use-billing-status.ts
- frontend/src/hooks/useAgentStream.ts
- frontend/src/lib/api-server.ts
- frontend/src/lib/api.ts
- frontend/src/providers/react-query-provider.tsx
This PR introduces:
- The fix for first token stream display on frontend
- Clean-up of tool side panels
- New scrape and crawl tool view, 
- New data provider tool view
- Improved icons and agent-start views
> First token stream fix

- frontend/src/components/thread/chat-input/file-upload-handler.tsx
- frontend/src/components/thread/chat-input/model-selector.tsx
Changes:
- Make chat input more responsive
> fix: responsive chat input

- frontend/src/components/thread/chat-input/message-input.tsx
- frontend/src/components/thread/chat-input/model-selector.tsx
Changes:
- Optimise upgrade message view for mobile
> fix: responsive free tier message

- frontend/src/app/(dashboard)/dashboard/_components/suggestions/examples.tsx
- frontend/src/app/(dashboard)/dashboard/page.tsx
- frontend/src/components/thread/chat-input/chat-input.tsx
This PR includes:
- Addition of a nice example section in dashboard page
> chore(ui): add example section in dashboard

- frontend/src/app/(dashboard)/agents/page.tsx
- frontend/src/components/maintenance/maintenance-page.tsx
- frontend/src/components/sidebar/nav-agents.tsx
- frontend/src/components/sidebar/search-search.tsx
- frontend/src/components/sidebar/share-modal.tsx
- frontend/src/components/thread/thread-site-header.tsx
- frontend/src/hooks/react-query/files/keys.ts
- frontend/src/hooks/react-query/files/use-sandbox-mutations.ts
- frontend/src/hooks/react-query/index.ts
- frontend/src/hooks/react-query/sidebar/keys.ts
- frontend/src/hooks/react-query/sidebar/use-project-mutations.ts
- frontend/src/hooks/react-query/sidebar/use-public-projects.ts
- frontend/src/hooks/react-query/subscriptions/use-billing.ts
- frontend/src/hooks/react-query/threads/use-thread-mutations.ts
- frontend/src/hooks/react-query/threads/use-thread-queries.ts
- frontend/src/hooks/react-query/usage/use-health.ts
- frontend/src/lib/api-enhanced.ts
This PR includes:
- Migration to react query
> chore(dev): move api calls to react query

- frontend/src/app/globals.css
- frontend/src/components/thread/content/ThreadContent.tsx
- frontend/src/components/ui/code-block.tsx
- frontend/src/components/ui/markdown.tsx
- frontend/src/hooks/use-cached-file.ts
Changes:
- Fix overflow issue
- File refetch issue
> fix: overflow issue and file refetch

- frontend/src/components/home/sections/hero-section.tsx
agent not starting on landing page - fix
> Content length fix

- frontend/src/hooks/use-cached-file.ts
Problem
The application's method of caching blob  , URLs in a global store was flawed, causing URLs to be revoked while still in use by other components, leading to broken UI and memory leaks that could crash the browser under heavy use.
Solution
- Store raw Blob objects in global cache instead of blob  URLs
- Create component-local blob   URLs from cached Blobs in useCachedFile hook
- Properly clean up local blob URLs on component unmount
- Maintains all existing functionality including background cache refresh and PDF handling
Result
Prevents premature URL revocation that caused broken images/files and potential browser crashes under heavy usage scenarios.
> fix: resolve blob URL memory leaks in file caching system

- backend/agent/sample_responses/1.txt
- backend/agent/sample_responses/2.txt
- backend/agent/sample_responses/3.txt
Correct tool call examples in sample response
> chore(dev): Correct tool call examples in sample response

- backend/agent/sample_responses/1.txt
- backend/agent/sample_responses/2.txt
- backend/agent/sample_responses/3.txt
- backend/api.py
Correct tool call examples in sample response
> Fix tool calls

- backend/services/billing.py
> fix(billing): update monthly usage calculation to exclude running jobs older than one hour

- backend/agent/tools/sb_vision_tool.py
- frontend/src/components/thread/tool-views/see-image-tool/_utils.ts
fixes #847 
https://github.com/user-attachments/assets/174ef0e0-d953-4f9e-b37a-8557eb865256
> Handle URL in see_image tool

- frontend/src/components/sidebar/kortix-logo.tsx
Check if the theme is system and change colour accordingly as mentioned in #884
> Fix icon theme if theme is system

- backend/agent/tools/sb_files_tool.py
- frontend/src/components/thread/file-viewer-modal.tsx
- frontend/src/components/thread/tool-views/utils.ts
fixes #888 
https://github.com/user-attachments/assets/da34c9e0-353a-4464-99dc-b79dcf141bde
> edge case: handle json file

- frontend/src/app/(dashboard)/projects/[projectId]/thread/[threadId]/page.tsx
fixes #921 
https://github.com/user-attachments/assets/c37e886a-2b33-40cf-a950-5e2f85ad7aa2
> fixed overflowing chatbox

- frontend/src/app/(dashboard)/agents/page.tsx
- frontend/src/components/agents/create-agent-dialog.tsx
- frontend/src/components/thread/chat-input/agent-selector.tsx
Add debouncing to all 'Create Agent' buttons to prevent accidental duplicate agent creation on rapid clicks.
---
[Slack Thread](https://kortixworkspace.slack.com/archives/C08QYH7MV6F/p1752747842131519?thread_ts=1752747842.131519&cid=C08QYH7MV6F)
> Implement debounce for agent creation

- frontend/src/components/ui/scroll-area.tsx
fixes #951 
https://github.com/user-attachments/assets/4b4eead7-b022-44da-b7ff-9aca34d4b2e7
> fix: horizontal scroll

- frontend/src/app/auth/page.tsx
Center buttons on the 'Check your email' page to fix alignment.
---
[Slack Thread](https://kortixworkspace.slack.com/archives/C09653SH1U3/p1752933277367149?thread_ts=1752933277.367149&cid=C09653SH1U3)
> Fix email page button alignment

- backend/agent/tools/sb_shell_tool.py
The `execute_command` tool (with `block=true`) spawns a session to run a shell command and determines completion by appending a unique marker (e.g., `COMMAND_DONE_<id>`) at the end of the command. It then monitors the **output** from the session to detect this marker string and treats it as the signal that execution is complete.
However, due to the way shell commands are echoed in the session output, the marker may appear in the echoed command itself—**before** the command has actually completed. Since the logic merely checks for the presence of the marker **anywhere in the output**, it may falsely conclude the command is done, even if it's still in progress.
Command:
```shell
cd /workspace && python -m pip install pandas openpyxl
```
Output:
```shell …
```
> fix: improve command completion detection in shell tool

- frontend/src/components/thread/content/ThreadContent.tsx
There's a serialization error in debug mode
> fix: stringify message in debug mode

- frontend/src/app/(dashboard)/agents/config/[agentId]/page.tsx
- frontend/src/components/agents/config/configuration-tab.tsx
- frontend/src/components/agents/mcp/tools-loader.tsx
- frontend/src/components/agents/mcp/tools-manager.tsx
- frontend/src/components/agents/pipedream/_components/app-card.tsx
- frontend/src/components/agents/pipedream/agent-pipedream-tools-manager.tsx
- frontend/src/components/agents/pipedream/pipedream-tool-selector.tsx
- frontend/src/components/ui/autosave-indicator.tsx
- frontend/src/components/ui/expandable-markdown-editor.tsx
- frontend/src/hooks/use-autosave.ts
This PR has:
- Auto save functionality in agent config page
- Improved Pipedream manager UI
> fix ux issues

- backend/agent/agent_builder_prompt.py
- backend/agent/custom_prompt.py
- backend/agent/gemini_prompt.py
- backend/agent/prompt.py
- backend/agent/run.py
- Add custom_prompt.py module for template variable processing
- Replace hardcoded year with {{current_year}} template variable
- Support {{current_date}}, {{current_time}}, {{current_year}} variables in customize new agent's system prompt.
- Ensure consistent datetime handling across all prompt files
- Fix prompt template inconsistencies
> feat: add dynamic datetime variables to agent prompts

- backend/agent/api.py
- backend/agent/utils.py
- backend/utils/config.py
- frontend/src/app/(dashboard)/projects/[projectId]/thread/[threadId]/page.tsx
- frontend/src/components/dashboard/dashboard-content.tsx
- frontend/src/components/home/sections/hero-section.tsx
- frontend/src/components/thread/agent-run-limit-dialog.tsx
- frontend/src/hooks/react-query/dashboard/use-initiate-agent.ts
- frontend/src/hooks/react-query/threads/use-agent-run.ts
- frontend/src/lib/api.ts
- frontend/src/lib/error-handler.ts
- Added functionality to check the maximum parallel agent runs allowed within a 24-hour period.
- Introduced `AgentRunLimitError` to handle cases where the limit is exceeded.
- Updated API to return appropriate error responses for agent run limits.
- Created `AgentRunLimitDialog` component to inform users when the limit is reached, displaying currently running agents and options to stop them.
- Integrated limit checks into agent initiation and running processes across relevant components.
> feat(agent-run-limits): implement agent run limit checks and UI dialogs

- backend/services/billing.py
- Updated `get_stripe_customer_id` function to accept a Supabase client and handle missing user_id metadata in Stripe customers.
- Added logic to create or update records in the `billing_customers` table based on Stripe customer data.
- Improved logging for customer metadata updates and billing record changes.
> Fix billing service to get customer data from Stripe if it's missing from DB

- backend/agent/suna/config.py
- backend/agent/tools/agent_builder_tools/credential_profile_tool.py
- backend/composio_integration/api.py
- backend/composio_integration/composio_service.py
- backend/composio_integration/connected_account_service.py
- backend/composio_integration/mcp_server_service.py
- backend/composio_integration/toolkit_service.py
- frontend/src/app/(dashboard)/settings/credentials/page.tsx
- frontend/src/components/agents/composio/composio-connections-section.tsx
- frontend/src/components/agents/composio/composio-connector.tsx
- frontend/src/components/agents/composio/composio-registry.tsx
- frontend/src/components/agents/composio/composio-tools-manager.tsx
- frontend/src/components/agents/custom-agents-page/marketplace-tab.tsx
- frontend/src/components/agents/installation/types.ts
- frontend/src/components/agents/marketplace-agent-preview-dialog.tsx
- frontend/src/components/agents/mcp/mcp-configuration-new.tsx
- frontend/src/components/workflows/workflow-builder.tsx
- frontend/src/components/workflows/workflow-definitions.ts
- frontend/src/components/workflows/workflow-side-panel.tsx
- frontend/src/hooks/react-query/composio/use-composio.ts
- frontend/src/lib/api-client.ts
This PR includes:
- UI/UX improvements for composio setup
> Composio integration

- backend/agent/api.py
- backend/agent/run.py
- backend/agent/utils.py
- backend/sandbox/tool_base.py
- backend/services/billing.py
- backend/utils/auth_utils.py
- backend/utils/cache.py
Lazily create sandbox for faster task creation
> feat: lazy sandbox initialization for faster task creation

- frontend/src/app/(dashboard)/layout.tsx
- frontend/src/app/api/edge-flags/route.ts
- frontend/src/components/dashboard/layout-content.tsx
- frontend/src/components/sidebar/nav-agents.tsx
- frontend/src/components/sidebar/search-search.tsx
- frontend/src/hooks/react-query/edge-flags/index.ts
- frontend/src/lib/edge-flags.ts
- Removed maintenance notice fetching from the DashboardLayout component.
- Introduced a new API route for fetching maintenance notice data.
- Updated DashboardLayoutContent to use a custom hook for maintenance notice queries.
- Adjusted data types for maintenance notice timestamps to strings for consistency.
- Added prefetching options in sidebar components for improved performance.
> fix: unnecessary prefetches and unnecessary RSCs

- backend/agent/api.py
- Combined total count retrieval and paginated data fetching into a single request for efficiency.
- Replaced per-agent version fetching with a batched query to reduce API calls and improve performance.
- Enhanced error handling for version data loading.
> refactor: optimize agent retrieval by batching version data queries

- backend/services/llm.py
fixes #1024 
used num_retries for retries
ref: [litellm](https://docs.litellm.ai/docs/completion/reliable_completions)
> refactor + add num_retries

- frontend/src/components/thread/tool-views/DeployToolView.tsx
fixing the depot tool to fetch preliminary link before "."
> deploy tool - fix link

- frontend/src/components/agents/agent-builder-chat.tsx
FIX: a lot of times the UI in manual config for agents is not updated after agent builder performed edits
> FIX:  agentbuilder update specs after tool calls

- backend/agent/tools/agent_builder_tools/agent_config_tool.py
a lot of times agent builder breaks stuff by completely rewriting the system prompt for an agent.
so I found this works better in production.
However, IMHO
agent builder gotta edit knowledge base instead of system prompt and keep system prompt uneditable for users
> Feature: System prompt append instead of replace for agent builder

- backend/agent/api.py
- backend/agent/services/agent_service.py
- backend/templates/api.py
- backend/templates/services/template_service.py
- backend/utils/pagination.py
- frontend/src/app/(dashboard)/agents/page.tsx
- frontend/src/components/agents/agents-grid.tsx
- frontend/src/components/agents/custom-agents-page/marketplace-tab.tsx
- frontend/src/components/agents/custom-agents-page/my-agents-tab.tsx
- frontend/src/components/agents/pagination.tsx
- frontend/src/components/dashboard/custom-agents-section.tsx
- frontend/src/hooks/react-query/agents/utils.ts
- frontend/src/hooks/react-query/secure-mcp/use-secure-mcp.ts
This PR:
- Fixes the pagination on agents & marketplace endpoints
> fix pagination in agents tab

- frontend/src/components/thread/tool-call-side-panel.tsx
https://github.com/user-attachments/assets/e56b49e2-adaa-4c42-9086-3ed6337104b0
> fix: tools not loading when refreshed

- frontend/src/components/sidebar/sidebar-left.tsx
> show burger
